name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t my-simple-app .

      - name: Run Docker container
        run: docker run -d -p 8080:8080 my-simple-app

      - name: Wait for the application to start
        run: sleep 10

      - name: Test containerized application
        run: curl -v http://localhost:8080
